= Ruby Belgeleri
İsmail Arılık <arilik.ismail@gmail.com>
0.1, 13 Mayıs, 2017, YazBel Ruby Belgeleri
:version-label: Sürüm
:last-update-label: Son güncelleme
:icons: font
:source-highlighter: pygments
:source-language: ruby
:toc: left
:toc-title: İçindekiler

// Font simgelerinin çalışması için eklenmiştir.
++++
<script src="https://use.fontawesome.com/c38eb8c034.js"></script>
++++

Ruby belgelerine hoşgeldiniz!

== Belgeler Hakkında

Bu belgelerin kaynak kodu https://github.com/yazbel/belgeler[GitHub'ta tutulmaktadır].

=== Nasıl yardım alabilirim?

Her zaman https://forum.yazbel.com/[YazBel forumu]nun https://forum.yazbel.com/c/ruby[Ruby kategorisi]nde bir konu açarak aklınızdaki soruları sorabilirsiniz.
Topluluk size yardım etmekten mutluluk duyacaktır.

=== Nasıl yardım edebilirim?

Birçok şekilde yardım edebilirsiniz:

- Belgelerde değişiklik yaparak çekme isteği(pull request) gönderebilirsiniz.
Yazım yanlışları ve küçük hatalar için GitHub arayüzünü kullanabilirsiniz ancak daha büyük ve karmaşık düzeltmeler için veri havuzunu bilgisayarınıza çekmeli, daha sonrasında düzeltmeleri yapıp çekme isteği göndermelisiniz.
Her iki durumda da kısa ve öz bir işleme mesajı(commit message) yazdığınıza emin olmalısınız.

- Eğer bir yanlış gördünüz ancak bir sebepten ötürü düzeltmeyi kendiniz yapmak istemediyseniz, bu hatayı bildirerek de yardım edebilirsiniz.
Bunun için veri havuzunun https://github.com/yazbel/belgeler/issues[konular(issues)] dizininde bir konu açın, başlık ve açıklama kısmına ilgili metinleri yazın ve gönderin.
Başlık kısmının kısa ve öz olmasına dikkat edin.
Ayrıca konuya, sağ taraftaki **Labels** bölümünden `ruby` etiketini eklediğinize de emin olun.

- https://forum.yazbel.com/c/ruby[Forumun Ruby kategorisi]nde sorulan soruları cevaplayabilirsiniz.

=== Lisans

https://github.com/yazbel/belgeler/blob/master/LICENSE[`LICENSE`] dosyasında da belirtildiği üzere bu belgelerin lisansı *Creative Commons Atıf-GayriTicari-AynıLisanslaPaylaş 4.0 Uluslararası (CC BY-NC-SA 4.0)* lisansıdır.
Daha fazla bilgi için lütfen dosyanın içeriğine bakınız.

== Ruby Hakkında

https://www.ruby-lang.org/tr/[Ruby], https://tr.wikipedia.org/wiki/Yukihiro_Matsumoto[Yukihiro Matsumoto] tarafından 1993 yılında Japonya'da tasarlanmaya ve geliştirilmeye başlanmıştır.
Verimlilik ve sadelik üzerine odaklanmış, açık kaynak kodlu dinamik bir dildir.
Okumayı ve yazmayı kolaylaştıran, doğal bir sözdizimine sahiptir.
Ayrıca günümüzün gözde programlama paradigmalarından olan nesneye yönelik programlama ve fonksiyonel programlama paradigmalarını güçlü bir şekilde desteklemektedir.
Ruby özgür bir yazılımdır ve https://www.ruby-lang.org/en/about/license.txt[Ruby lisansı] ile lisanslanmıştır.
